# Generated by Django 2.2.2 on 2019-06-18 09:38

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lavatory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('building_name', models.CharField(default='', max_length=255, verbose_name='Building name')),
                ('floor', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-99), django.core.validators.MaxValueValidator(99)], verbose_name='Floor')),
                ('urinals_num', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Number of urinals')),
                ('bowls_num', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Number of toilet bowls')),
                ('jp_styles_num', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Number of japanese style toilets')),
                ('wash_num', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Number of wash basins')),
                ('score_ave', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Average score')),
                ('create_user_id', models.IntegerField(default=0, verbose_name='User id')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('confirmed_flg', models.BooleanField(default=False, verbose_name='Confirmed')),
                ('del_flg', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
        ),
    ]
