# Generated by Django 2.2.2 on 2019-06-18 12:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon')),
                ('del_flg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavatory_id', models.IntegerField()),
                ('total_score', models.FloatField(blank=True, choices=[(0, '最悪'), (1, 'ひどい'), (2, 'あまり良くない'), (3, '普通'), (4, '良い'), (5, '非常に良い')], null=True)),
                ('beautiful_score', models.IntegerField(blank=True, choices=[(0, '最悪'), (1, 'ひどい'), (2, 'あまり良くない'), (3, '普通'), (4, '良い'), (5, '非常に良い')], null=True)),
                ('access_score', models.IntegerField(blank=True, choices=[(0, '最悪'), (1, 'ひどい'), (2, 'あまり良くない'), (3, '普通'), (4, '良い'), (5, '非常に良い')], null=True)),
                ('abilability_score', models.IntegerField(blank=True, choices=[(0, '最悪'), (1, 'ひどい'), (2, 'あまり良くない'), (3, '普通'), (4, '良い'), (5, '非常に良い')], null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('del_flg', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
    ]
